apps/hellgate/test/hg_ct_helper.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, apps/hg_client/src/hg_client_api.erl
This reverts commit 952fc984f5dbbb2b7a153d662e77a38d9a794679.
Нужно вмержить https://github.com/rbkmoney/hellgate/pull/374 перед этим коммитом.
=> Revert "HG-516: pass transport_opts in hg_client_api (#371)"

apps/hellgate/test/hg_ct_helper.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, apps/hg_client/src/hg_client_api.erl
=> Revert "Revert "HG-516: pass transport_opts in hg_client_api (#371)""

apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_recurrent_paytool.erl, apps/hellgate/src/hg_routing.erl, apps/hellgate/test/hg_ct_helper.erl, apps/hellgate/test/hg_direct_recurrent_tests_SUITE.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, apps/hellgate/test/hg_routing_tests_SUITE.erl, test/machinegun/config.yaml
Temporary reverts rbkmoney/hellgate#373
=> Revert "HG-518: Route change reporting"

apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl
This fixes change from rbkmoney/hellgate#356
=> Add back activity check in cancel start

apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_recurrent_paytool.erl, apps/hellgate/src/hg_routing.erl, apps/hellgate/test/hg_ct_helper.erl, apps/hellgate/test/hg_direct_recurrent_tests_SUITE.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, apps/hellgate/test/hg_routing_tests_SUITE.erl, test/machinegun/config.yaml
=> Revert "Revert "HG-518: Route change reporting""

apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_routing.erl, apps/hellgate/test/hg_direct_recurrent_tests_SUITE.erl, rebar.lock
This reverts commit 3460f019f079187557d8dee65a8f744efe40a9fb.
=> HG-469: Revert recurrent route validation

rebar.lock
Add rbkmoney/damsel#546 changes support
=> FF-164 Update damsel

apps/hellgate/src/hg_routing.erl, apps/hellgate/test/hg_routing_tests_SUITE.erl
... instead of failing with fucntion clause
=> Interpret `undefined` selector as a reason for route rejecting

apps/hellgate/src/hg_invoice_payment.erl
Also remove invoice timestamp usage in refund and payment terms computation
=> Use explicit timestamp to compute merchant terms

apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl
This reverts commit 7f23d74bf7246df59ee11eb368ac82a8e5cd0865.
=> Temporarily revert second part of HG-538

apps/party_management/src/pm_selector.erl, apps/party_management/test/pm_ct_domain.erl, apps/party_management/test/pm_ct_domain.hrl, apps/party_management/test/pm_ct_fixture.erl, apps/party_management/test/pm_ct_helper.erl, apps/party_management/test/pm_party_tests_SUITE.erl, docker-compose.sh
Following rbkmoney/damsel#582.
=> DC-120: Implement criteria in predicates

apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_routing.erl, apps/hellgate/test/hg_customer_tests_SUITE.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl
Reverts rbkmoney/hellgate#462
Antifraud config doesn't ready .
=> Revert "HG-543: check risk score for predefined route"

apps/party_management/src/pm_party_handler.erl
Первый PR на выкатку в рамках рефакторинга ComputeShopTerms
=> HG-555: Handle Varset in ComputeShopTerms

docker-compose.sh, rebar.config
- обновление build-utils 
- актуализация версий тестовых образов 
- автоформатирование rebar.config
=> update build env

apps/hellgate/src/hg_payment_tool.erl, apps/hellgate/test/hg_ct_domain.hrl, apps/hellgate/test/hg_dummy_provider.erl, apps/hellgate/test/hg_invoice_template_tests_SUITE.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, apps/hellgate/test/hg_recurrent_paytools_tests_SUITE.erl, apps/hellgate/test/hg_route_rules_tests_SUITE.erl, apps/hellgate/test/hg_routing_tests_SUITE.erl, apps/party_management/src/pm_payment_tool.erl, apps/party_management/src/pm_selector.erl, apps/party_management/src/pm_varset.erl, apps/party_management/test/pm_claim_committer_SUITE.erl, apps/party_management/test/pm_ct_domain.hrl, apps/party_management/test/pm_party_tests_SUITE.erl, rebar.lock
Тут только обновление протокола, переход на новые справочники будет отдельно
=> ED-102: Update damsel

apps/party_management/include/legacy_party_structures.hrl, apps/party_management/include/party_events.hrl, apps/party_management/src/pm_maybe.erl, apps/party_management/src/pm_party_machine.erl, apps/party_management/test/pm_ct_helper.erl, apps/party_management/test/pm_eventsink_history.erl, apps/party_management/test/pm_party_tests_SUITE.erl, apps/pm_client/src/pm_client_eventsink.erl, apps/pm_proto/.gitignore, apps/pm_proto/Makefile, apps/pm_proto/include/dmsl_base_thrift.hrl, apps/pm_proto/include/dmsl_domain_thrift.hrl, apps/pm_proto/include/dmsl_payment_processing_thrift.hrl, apps/pm_proto/proto/party_state.thrift, apps/pm_proto/rebar.config, apps/pm_proto/src/pm_proto.erl, elvis.config, rebar.config, rebar.lock
Also encode party state snapshots as thrift binary from now on.
=> Bump to rbkmoney/damsel@cc2875b carefully

apps/party_management/src/pm_party_machine.erl, apps/party_management/test/pm_party_tests_SUITE.erl
=> Fix get revision w/ empty index

apps/hellgate/include/customer_events.hrl, apps/hellgate/include/domain.hrl, apps/hellgate/include/invoice_events.hrl, apps/hellgate/include/legacy_structures.hrl, apps/hellgate/include/party_events.hrl, apps/hellgate/include/payment_events.hrl, apps/hellgate/include/recurrent_payment_tools.hrl, apps/hellgate/src/hg_cashflow.erl, apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_invoice_payment_chargeback.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, rebar.config, rebar.lock
This reverts commit 843ab7ceb0b09217161149cd38c6e787eda07541.
#	apps/hellgate/test/hg_invoice_tests_SUITE.erl
=> Revert "ED-69: Implement new cashflow (#577)"

apps/hellgate/include/customer_events.hrl, apps/hellgate/include/domain.hrl, apps/hellgate/include/invoice_events.hrl, apps/hellgate/include/legacy_structures.hrl, apps/hellgate/include/party_events.hrl, apps/hellgate/include/payment_events.hrl, apps/hellgate/include/recurrent_payment_tools.hrl, apps/hellgate/src/hg_cashflow.erl, apps/hellgate/src/hg_invoice.erl, apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_invoice_payment_chargeback.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, rebar.config, rebar.lock
This reverts commit a76f6ee905f3bcdb32707abc65ac4930eeb5c255.
=> ED-69: Implement Cashflow

apps/hellgate/src/hg_accounting.erl, apps/hellgate/src/hg_cashflow.erl, apps/hellgate/src/hg_customer.erl, apps/hellgate/src/hg_domain.erl, apps/hellgate/src/hg_invoice.erl, apps/hellgate/src/hg_invoice_payment.erl, apps/hellgate/src/hg_limiter.erl, apps/hellgate/src/hg_routing.erl, apps/hellgate/test/hg_ct_helper.erl, apps/hellgate/test/hg_invoice_tests_SUITE.erl, docker-compose.sh, rebar.config, rebar.lock
обновлен damsel до последней версии включающей payout
обновлен format
=> ED-245: +rbkmoney/damsel#700 +format
